import jwt


token = "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiaXNzIjoiaHR0cHM6Ly9kZXYtdzVpaWw2YmFwcW5mMm5haS51cy5hdXRoMC5jb20vIn0..kVdBaQxtRhpsNuSS.p65-7I0FR3ZZCxNZ0HOC7N1ry-fIoVvMEmhQfAyKN3X4B-OkLkCHYBWsJwVwQlwnafngjC-1iH-HJIpmMH8KeHyumNMN3CND9Oc8mW_MEvVO_qDeNBQXPMuMTiTuuG1ABnW6MnfbqLDTKUP-nboxgi6iBmuV-tN3DYAGq2XmQJTyTXyO9PDyR7MZ2KhDoJrNNc5Yj-WX2qjRZ5dDku0d092E4VldKvYCVkYy5jajdtoqn1EafEl1VlSOcY6Iso3ezdKQQiClqgYq-ywQvJbIfqESukAnFQ_JRlklp2YVnYx8QaJesx2Y5g3l8t-Tma4wWIjP.rg4HYDN-pGgUT_FyBpQUgg"

decoded_token = jwt.decode(token, algorithms=['RS256'], verify=False)
payload = decoded_token.get("payload_key")

print(payload)







