apiVersion: v1
kind: List
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: auth-api
      labels:
        api: auth-api
    spec:
      selector:
        matchLabels:
          api: auth-api
      replicas: 1
      template:
        metadata:
          labels:
            api: auth-api
        spec:
          containers:
            - name: auth-api
              image: {{ .Values.auth.containers.image }}
              imagePullPolicy: Always
              ports:
                - name: auth-api
                  containerPort: 8000
                  protocol: TCP
  - apiVersion: v1
    kind: Service
    metadata:
      name: auth-api
    spec:
      ports:
        - port: 8000
          targetPort: 8000
          name: auth-api
      selector:
        api: auth-api
      type: ClusterIP
