apiVersion: v1
kind: Namespace
metadata:
  name: compute
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-access-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - get
  - list
  - watch
  - exec
  - attach

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-access-service-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-access-role-binding
subjects:
- kind: ServiceAccount
  name: pod-access-service-account
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-access-role
  apiGroup: rbac.authorization.k8s.io
