apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-10gb1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: Service
metadata:
  name: postgres1
spec:
  ports:
    - name: tcp
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    name: postgres1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres1
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      name: postgres1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: postgres1
    spec:
      containers:
        - env:
            - name: POSTGRESQL_USERNAME
              value: {{ .Values.postgres1.envVars.POSTGRES_USER | quote  }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.postgres1.envVars.POSTGRES_PASSWORD | quote  }}
            - name: POSTGRESQL_DATABASE
              value: {{ .Values.postgres1.envVars.POSTGRES_DB | quote  }}
          image: bitnami/postgresql:13.2.0
          imagePullPolicy: IfNotPresent
          name: postgres1
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 250Mi
          volumeMounts:
            - mountPath: /bitnami/postgresql
              name: persistent-postgres-database-1
      dnsPolicy: ClusterFirst
      hostname: postgres1
      restartPolicy: Always
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      terminationGracePeriodSeconds: 30
      volumes:
        - name: persistent-postgres-database-1
          persistentVolumeClaim:
            claimName: pvc-10gb1
