---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  labels:
    app: web-api
spec:
  selector:
    matchLabels:
      app: web-api
  replicas: 1
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
        - name: web-api
          image: {{ .Values.goAPI.containers.image | quote }}
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.goAPI.envVars.POSTGRES_HOST | quote  }}
            - name: POSTGRES_PORT
              value: {{ .Values.goAPI.envVars.POSTGRES_PORT | quote  }}
            - name: POSTGRES_DB
              value: {{ .Values.goAPI.envVars.POSTGRES_DB | quote  }}
            - name: POSTGRES_USER
              value: {{ .Values.goAPI.envVars.POSTGRES_USER | quote  }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.goAPI.envVars.POSTGRES_PASSWORD | quote  }}

          ports:
            - name: web-api
              containerPort: 8080
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: web-api
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: web-api
  selector:
    app: web-api
  type: ClusterIP
